whosonfirst-data/whosonfirst-data-admin-in

data/102/030/425/102030425-alt-quattroshapes.geojson

Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/1764.
No PIP required, can merge now.

Fix invalid json in alt

---

data/124/282/545/7/1242825457.geojson
data/129/354/753/3/1293547533.geojson

Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/1788
Updates names, variant and preferred names, and is_current properties in two locality records in India. No PIP work required, can merge once approved.

Updated locality names

---

data/134/373/049/7/1343730497.geojson

Updating `data/134/373/049/7/1343730497.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Zerakpur

---

data/129/364/746/5/1293647465.geojson

Updating `data/129/364/746/5/1293647465.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Bajowali

---

data/129/375/206/7/1293752067.geojson

Updating `data/129/375/206/7/1293752067.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Gandho

---

data/124/293/155/5/1242931555.geojson

Updating `data/124/293/155/5/1242931555.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Jhanbke

---

data/124/263/004/9/1242630049.geojson

Updating `data/124/263/004/9/1242630049.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Bisrakh

---

data/859/039/99/85903999.geojson

Updating `data/859/039/99/85903999.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Warli

---

data/127/716/420/9/1277164209.geojson

Updating `data/127/716/420/9/1277164209.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Bilaur

---

data/129/383/241/9/1293832419.geojson

Updating `data/129/383/241/9/1293832419.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Pagrapalli

---

data/131/046/019/3/1310460193.geojson

Updating `data/131/046/019/3/1310460193.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Mataura

---

data/112/605/471/3/1126054713.geojson

Updating `data/112/605/471/3/1126054713.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Bholapur

---

data/127/714/458/1/1277144581.geojson

Updating `data/127/714/458/1/1277144581.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Yigavaripalem

---

data/124/312/818/7/1243128187.geojson

Updating `data/124/312/818/7/1243128187.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Bhanoke

---

data/890/506/321/890506321.geojson

Updating `data/890/506/321/890506321.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Sanibar Peth

---

data/127/640/791/3/1276407913.geojson

Updating `data/127/640/791/3/1276407913.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Titli

---

data/127/639/724/3/1276397243.geojson

Updated names for locality record in India.

Update names on IN locality

---

data/119/318/903/9/1193189039.geojson

Updating `data/119/318/903/9/1193189039.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Chevella

---

data/119/302/837/7/1193028377.geojson

Updating `data/119/302/837/7/1193028377.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Pentapadu Kasba

---

data/129/326/032/3/1293260323.geojson

Updating `data/129/326/032/3/1293260323.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Goluwali

---

data/129/334/646/1/1293346461.geojson

Updating `data/129/334/646/1/1293346461.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Mandl Gobindgarh

---

data/122/641/079/9/1226410799.geojson

Updating `data/122/641/079/9/1226410799.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Kilanwati

---

data/151/138/265/5/1511382655.geojson

Updating `data/151/138/265/5/1511382655.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Vansathalipuram

---

data/134/371/803/5/1343718035.geojson

Updating `data/134/371/803/5/1343718035.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Khokri Kalan

---

data/132/730/236/5/1327302365.geojson

Updating `data/132/730/236/5/1327302365.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Kuthiala

---

data/132/679/897/5/1326798975.geojson

Updating `data/132/679/897/5/1326798975.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Karmunwala

---

data/131/043/405/3/1310434053.geojson

Updating `data/131/043/405/3/1310434053.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Haldwaoi Talli

---

data/134/330/211/7/1343302117.geojson

Updating `data/134/330/211/7/1343302117.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Batesar

---

data/129/316/924/7/1293169247.geojson

Updating `data/129/316/924/7/1293169247.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Dhodda

---

data/129/294/369/7/1292943697.geojson

Updating `data/129/294/369/7/1292943697.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Lelanga

---

data/125/935/121/5/1259351215.geojson

Updating `data/125/935/121/5/1259351215.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Samdu

---

data/136/015/317/5/1360153175.geojson

Updating `data/136/015/317/5/1360153175.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Wirk Khurd

---

data/129/374/196/1/1293741961.geojson

Updating `data/129/374/196/1/1293741961.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Urpaar

---

data/102/030/979/102030979.geojson

Updating `data/102/030/979/102030979.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Amarnath

---

data/134/411/306/7/1344113067.geojson

Updating `data/134/411/306/7/1344113067.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Gurram

---

data/122/672/197/3/1226721973.geojson

Updating `data/122/672/197/3/1226721973.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Vagholi

---

data/134/372/021/7/1343720217.geojson

Updating `data/134/372/021/7/1343720217.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Chandarwal

---

data/102/030/459/102030459.geojson

Updating `data/102/030/459/102030459.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Dāhod

---

data/125/974/139/5/1259741395.geojson

Updating `data/125/974/139/5/1259741395.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Fatehwal

---

data/127/695/707/9/1276957079.geojson

Updating `data/127/695/707/9/1276957079.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Pewant

---

data/134/370/418/3/1343704183.geojson

Updating `data/134/370/418/3/1343704183.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Tekulabodu

---

data/136/013/574/7/1360135747.geojson

Updating `data/136/013/574/7/1360135747.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Garmelapalli

---

data/110/869/629/7/1108696297.geojson

Updating `data/110/869/629/7/1108696297.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Garhchiroli

---

data/122/588/410/9/1225884109.geojson

Updating `data/122/588/410/9/1225884109.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Ghure Patti

---

data/127/650/267/5/1276502675.geojson

Updating `data/127/650/267/5/1276502675.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Wirpal

---

data/125/977/202/3/1259772023.geojson

Updating `data/125/977/202/3/1259772023.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Paltra

---

data/127/618/267/9/1276182679.geojson

Updating `data/127/618/267/9/1276182679.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Upal

---

data/131/035/885/7/1310358857.geojson

Updating `data/131/035/885/7/1310358857.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Kharti Piplia

---

data/127/671/981/9/1276719819.geojson

Updating `data/127/671/981/9/1276719819.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Chamal Kalan

---

data/136/024/095/9/1360240959.geojson

Updating `data/136/024/095/9/1360240959.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Odhuwal

---

data/122/619/808/5/1226198085.geojson

Updating `data/122/619/808/5/1226198085.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Mujasar

---

data/129/327/829/1/1293278291.geojson

Updating `data/129/327/829/1/1293278291.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Valakkad

---

data/122/591/231/3/1225912313.geojson

Updating `data/122/591/231/3/1225912313.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Morjhanda

---

data/131/066/918/9/1310669189.geojson

Updating `data/131/066/918/9/1310669189.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Phutlawa

---

data/102/030/739/102030739.geojson

Updating `data/102/030/739/102030739.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Belgaum

---

data/131/036/358/1/1310363581.geojson

Updating `data/131/036/358/1/1310363581.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Chamkor

---

data/131/036/155/3/1310361553.geojson

Updating `data/131/036/155/3/1310361553.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Bara Patarai

---

data/129/393/951/9/1293939519.geojson

Updating `data/129/393/951/9/1293939519.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Bangowali

---

data/124/261/806/3/1242618063.geojson

Updating `data/124/261/806/3/1242618063.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Karmeri

---

data/122/668/834/1/1226688341.geojson

Updating `data/122/668/834/1/1226688341.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Chautapal

---

data/134/362/980/5/1343629805.geojson

Updating `data/134/362/980/5/1343629805.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Attipur

---

data/124/307/019/1/1243070191.geojson

Updating `data/124/307/019/1/1243070191.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Virannapalem

---

data/102/030/995/102030995.geojson
data/890/510/339/890510339.geojson

This PR updates name translations on a locality and county record in India, to match "official" naming conventions. Existing preferred names were moved to variant namespaces, and a handful of new preferred names were added, when available.
No PIP work required, can merge once approved.

Update names, labels for two records in IN

---

data/102/030/115/102030115.geojson

Updating `data/102/030/115/102030115.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)
**Number of records updated**: 1

Update Place Haridwār

---

data/110/869/569/7/1108695697.geojson
data/110/869/570/9/1108695709.geojson
data/110/869/571/9/1108695719.geojson
data/110/869/572/3/1108695723.geojson
data/110/869/572/9/1108695729.geojson
data/110/869/573/1/1108695731.geojson
data/110/869/573/7/1108695737.geojson
data/110/869/587/3/1108695873.geojson
data/110/869/599/1/1108695991.geojson
data/110/869/602/7/1108696027.geojson
data/110/869/604/9/1108696049.geojson
data/110/869/606/9/1108696069.geojson
data/110/869/607/5/1108696075.geojson
data/110/869/614/3/1108696143.geojson
data/110/869/618/1/1108696181.geojson
data/110/869/618/9/1108696189.geojson
data/110/869/626/7/1108696267.geojson
data/110/869/627/3/1108696273.geojson
data/110/869/636/7/1108696367.geojson
data/179/679/783/7/1796797837.geojson
data/890/507/399/890507399.geojson
data/890/509/223/890509223.geojson
data/890/510/039/890510039.geojson
data/890/510/339/890510339.geojson
data/890/510/611/890510611.geojson

Will fix a portion of https://github.com/whosonfirst-data/whosonfirst-data/issues/2154. Sets placetype local, names, populations, and statoids properties for CARTO

in placetype local and more

---

data/102/030/819/102030819.geojson

Replaces #139, because GH.com funk...

Update Place Bangalore

---

data/890/506/443/890506443.geojson

Updating `data/890/506/443/890506443.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

Update Place Delhi
